function createAbilityHandlerContext(params = {}) {
  const {
    players,
    mobs,
    projectiles,
    mapWidth,
    mapHeight,
    defaultProjectileHitRadius,
    allocateProjectileId,
    clamp,
    normalizeDirection,
    randomInt,
    rotateDirection,
    getAbilityRangeForLevel,
    getAbilityDamageRange,
    getAbilityDamageRangeForEntity,
    getAbilityDotDamageRange,
    getAbilityDotDamageRangeForEntity,
    getAbilityChainStatsForEntity,
    markAbilityUsed,
    applyDamageToMob,
    applyAbilityHitEffectsToMob,
    applyDamageToPlayer,
    stunMob,
    stunPlayer,
    queueExplosionEvent,
    getAreaAbilityTargetPosition,
    createPersistentAreaEffect,
    createPersistentBeamEffect,
    createPersistentSummonEffect,
    resolvePlayerMobCollisions,
    applySelfBuffs,
    getAbilityInvulnerabilityDurationMs,
    isPlayerEnemy
  } = params;

  return {
    players,
    mobs,
    projectiles,
    mapWidth,
    mapHeight,
    defaultProjectileHitRadius,
    allocateProjectileId,
    clamp,
    normalizeDirection,
    randomInt,
    rotateDirection,
    getAbilityRangeForLevel,
    getAbilityDamageRange,
    getAbilityDamageRangeForEntity,
    getAbilityDotDamageRange,
    getAbilityDotDamageRangeForEntity,
    getAbilityChainStatsForEntity,
    markAbilityUsed,
    applyDamageToMob,
    applyAbilityHitEffectsToMob,
    applyDamageToPlayer,
    stunMob,
    stunPlayer,
    queueExplosionEvent,
    getAreaAbilityTargetPosition,
    createPersistentAreaEffect,
    createPersistentBeamEffect,
    createPersistentSummonEffect,
    resolvePlayerMobCollisions,
    applySelfBuffs,
    getAbilityInvulnerabilityDurationMs,
    isPlayerEnemy
  };
}

module.exports = {
  createAbilityHandlerContext
};
