function createWsConnectionDeps({
  getClassConfig,
  getAbilityConfig,
  getItemConfig,
  allocatePlayerId,
  createPlayer,
  createBotPlayer,
  createBenchmarkScene,
  listBots,
  inspectBot,
  destroyBot,
  setBotFollow,
  clearBotFollow,
  sendJson,
  players,
  mapWidth,
  mapHeight,
  visibilityRange,
  buildSoundManifest,
  randomSpawn,
  expNeededForLevel,
  createEmptyInventorySlots,
  createEmptyEquipmentSlots,
  normalizeItemEntries,
  addItemsToInventory,
  syncPlayerCopperFromInventory,
  sendInventoryState,
  sendEquipmentState,
  sendSelfProgress,
  clamp,
  normalizeDirection,
  clearPlayerCast,
  usePlayerAbility,
  updatePlayerCastTarget,
  levelUpPlayerAbility,
  tryPickupLootBag,
  getVendorNpc,
  isPlayerNearVendor,
  getInventoryEntrySellValue,
  sellInventoryItemToVendor,
  mergeOrSwapInventorySlots,
  equipInventoryItem,
  unequipEquipmentItem,
  consumeInventoryItem,
  addHealOverTimeEffect,
  addManaOverTimeEffect
}) {
  return {
    sendJson,
    players,
    get CLASS_CONFIG() {
      return getClassConfig();
    },
    get ABILITY_CONFIG() {
      return getAbilityConfig();
    },
    get ITEM_CONFIG() {
      return getItemConfig();
    },
    MAP_WIDTH: mapWidth,
    MAP_HEIGHT: mapHeight,
    VISIBILITY_RANGE: visibilityRange,
    buildSoundManifest,
    randomSpawn,
    expNeededForLevel,
    createEmptyInventorySlots,
    createEmptyEquipmentSlots,
    normalizeItemEntries,
    addItemsToInventory,
    syncPlayerCopperFromInventory,
    sendInventoryState,
    sendEquipmentState,
    sendSelfProgress,
    clamp,
    normalizeDirection,
    clearPlayerCast,
    usePlayerAbility,
    updatePlayerCastTarget,
    levelUpPlayerAbility,
    tryPickupLootBag,
    getVendorNpc,
    isPlayerNearVendor,
    getInventoryEntrySellValue,
    sellInventoryItemToVendor,
    mergeOrSwapInventorySlots,
    equipInventoryItem,
    unequipEquipmentItem,
    consumeInventoryItem,
    addHealOverTimeEffect,
    addManaOverTimeEffect,
    allocatePlayerId,
    createPlayer,
    createBotPlayer,
    createBenchmarkScene,
    listBots,
    inspectBot,
    destroyBot,
    setBotFollow,
    clearBotFollow
  };
}

module.exports = {
  createWsConnectionDeps
};
